version: "3"
services:
  # front:
  #   image: "us-central1-docker.pkg.dev/inspiring-tower-411321/myservice/front:latest"
  #   build: ./productManager
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - product
  product:
    image: "us-central1-docker.pkg.dev/inspiring-tower-411321/myservice/product:latest"
    build: ./Products
    container_name: product
    ports:
      - "8080:8084"
    depends_on:
      - config
      - postgres_product
  auth:
    image: "us-central1-docker.pkg.dev/inspiring-tower-411321/myservice/auth:latest"
    build: ./Auth
    container_name: auth
    ports:
      - "8080:8090"
    depends_on:
      - config
      - postgres_auth
  config:
    image: "us-central1-docker.pkg.dev/inspiring-tower-411321/myservice/config:latest"
    build: ./Config
    container_name: config
    ports:
      - "8080:8888"
  postgres_product:
    image: "us-central1-docker.pkg.dev/inspiring-tower-411321/myservice/postgress-product:latest"
    build: ./postgress-product
    container_name: postgres.product
    ports:
      - "8080:5432"
  postgres_auth:
    image: "us-central1-docker.pkg.dev/inspiring-tower-411321/myservice/postgress-auth:latest"
    build: ./postgress-auth
    container_name: postgres.auth
    ports:
      - "8080:5432"
